### ISSUE TITLE
Dead link to github on the website (Atlas Gonnect)

### ISSUE THREAD

**Issue by Lou-M** [craftamap/atlas-gonnect#11]
Gemeint ist die Website: https://siegelfabian.de/projects/2020/atlas-gonnect/

> **Atlas Gonnect**
> Atlas Gonnect ist eine Implementierung des Atlassian-Connect-Frameworks in der Sprache Golang.
> [Finde Atlas-Gonnect auf github.com](https://siegelfabian.de/projects/2020/atlas-gonnect/github.com/craftamap/atlas-gonnect)

Der Link hinter "Finde Atlas-Gonnect [...]" führt zu dieser Fehlermeldung: 
> **Not found**
> The requested URL was not found on this server.

Screenshot:
![image](https://user-images.githubusercontent.com/73669620/186840661-e0e0b09a-26d2-42c2-bb09-eed7ea3b2b2d.png)

**Comment by craftamap** [comment]
Fixed, thank you!
